dashboard/urls.py
from django.urls import path
from .views import dashboard, getChartData

app_name = "dashboard"

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("chart/", getChartData.as_view(), name="getChartData"),
]

employee_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from allauth.account.views import LoginView
from django.views import defaults


def pageNotFound(request):
    return defaults.page_not_found(request, None)


def serverError(request):
    return defaults.server_error(request)


urlpatterns = [
    path('admin/', admin.site.urls),
    path("employee/", include("employee.urls", namespace="employee")),
    path("inventory/", include("inventory.urls", namespace="inventory")),
    path("apiTools/", include("apiTools.urls", namespace="apiTools")),
    path("dashboard/", include("dashboard.urls", namespace="dashboard")),
    path("userRoles/", include("userRoles.urls", namespace="userRoles")),
    path("bgeForms/", include("bgeForms.urls", namespace="bgeForms")),
    path("iberForms/", include("iberForms.urls", namespace="iberForms")),
    path("pstForms/", include("pstForms.urls", namespace="pstForms")),
    path("pinergyForms/", include("pinergyForms.urls", namespace="pinergyForms")),
    path("reports/", include("reports.urls", namespace="reports")),
    path('accounts/', include('allauth.urls')),
    path("", LoginView.as_view(), name="login"),
    path("404/", pageNotFound),
    path("500/", serverError),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

reports/urls.py
from django.urls import path
from .views import (attendance_report,
                    report_list,
                    draw_attendance_report,
                    leaver_report,
                    draw_leaver_report)

app_name = "reports"

urlpatterns = [
    path("report_list/", report_list, name="report_list"),
    path("attendance_report/", attendance_report, name="attendance_report"),
    path("leaver_report/", leaver_report, name="leaver_report"),
    path("draw_attendance_report/", draw_attendance_report,
         name="draw_attendance_report"),
    path("draw_leaver_report/", draw_leaver_report,
         name="draw_leaver_report"),
]

reports/models.py
from django.db import models

# Create your models here.

reports/forms.py
from django import forms
from employee.models import Department, Employee

payroll = (
    ("F", "Fortnightly"),
    ("M", "Monthly"),
)


class AttendanceReportForm(forms.Form):
    """ Form to get the attendance report for payroll. """

    start_date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}))
    end_date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}))
    employee = forms.ModelChoiceField(
        queryset=Employee.objects.all(), required=False)
    department = forms.ModelChoiceField(
        Department.objects.all(), required=False)
    payroll_type = forms.ChoiceField(choices=payroll, required=True)


class LeaverReportForm(forms.Form):
    """ Form to get the attendance report for payroll. """

    start_date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}))
    end_date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}))
    employee = forms.ModelChoiceField(
        queryset=Employee.objects.all(), required=False)
    department = forms.ModelChoiceField(
        Department.objects.all(), required=False)

reports/views.py
from django.db.models import Sum
from django.db.models.query_utils import Q
from django.http.response import HttpResponse
from django.shortcuts import render
from datetime import datetime, timedelta
from openpyxl import Workbook
from openpyxl.writer.excel import save_virtual_workbook
from openpyxl.utils import get_column_letter
from openpyxl.styles import Font, Alignment, Border, Side, PatternFill
from employee.models import AttendanceStatus, EmployeeAttendance, EmployeeLeave
from reports.forms import AttendanceReportForm, LeaverReportForm
from userRoles.views import getUserType
from django.contrib.auth.decorators import login_required, user_passes_test


def userHasAccess(user):

    if (getUserType(user) == "HR" or
            user.is_superuser):
        return True
    else:
        return False


@login_required
@user_passes_test(userHasAccess,
                  login_url="/dashboard/",
                  redirect_field_name=None)
def report_list(request):
    """Render a list with all reports available."""

    context = {
        "reports": {
            "Attendance Report": "reports:attendance_report",
            "Leaver Report": "reports:leaver_report"
        }
    }

    return render(request, 'reports/report_list.html', context)


@login_required
@user_passes_test(userHasAccess,
                  login_url="/dashboard/",
                  redirect_field_name=None)
def attendance_report(request):
    """Render a form with filter for the attendance report."""

    form = AttendanceReportForm()

    if request.method == "POST":
        form = AttendanceReportForm(request.POST)

    context = {
        "form": form
    }

    return render(request, 'reports/attendance_report.html', context)


@login_required
def leaver_report(request):
    """Render a form with filter for the leaver report."""

    form = LeaverReportForm()

    if request.method == "POST":
        form = LeaverReportForm(request.POST)

    context = {
        "form": form
    }

    return render(request, 'reports/leaver_report.html', context)


def get_employee_attendances(request):
    """Return a object with all employees and their attendances."""

    if request.method == "POST":

        filters = (Q(attendance_date__gte=request.POST.get("start_date")) &
                   Q(attendance_date__lte=request.POST.get("end_date")))

        employee_id = None if request.POST.get(
            'employee') == "" else request.POST.get('employee')
        department = None if request.POST.get(
            "department") == "" else request.POST.get("department")
        payroll_type = None if request.POST.get(
            "payroll_type") == "" else request.POST.get("payroll_type")

        if employee_id is not None:
            filters = filters & Q(employee_id=employee_id)
        if department is not None:
            filters = filters & Q(employee__department=department)
        if payroll_type is not None:
            filters = filters & Q(employee__payroll_type=payroll_type)

        employee_attendances = EmployeeAttendance.objects.filter(
            filters).prefetch_related('employee').order_by(
                "employee__first_name", "attendance_date").values(
                    "employee__first_name",
                    "employee__last_name",
                    "employee__id",
                    "employee__manager__first_name",
                    "employee__manager__last_name",
                    "attendance_date",
                    "status__status_name",
                    "hours_worked",
                    "additional_status__status_name",
                    "additional_hours_worked",
                    "notes"
        ).distinct()

        return employee_attendances


def get_employee_leave(request):
    """Return a object with all employees and their leave."""

    if request.method == "POST":

        filters = (Q(start_date__gte=request.POST.get("start_date")) &
                   Q(start_date__lte=request.POST.get("end_date")))

        employee_id = None if request.POST.get(
            'employee') == "" else request.POST.get('employee')
        department = None if request.POST.get(
            "department") == "" else request.POST.get("department")

        if employee_id is not None:
            filters = filters & Q(employee_id=employee_id)
        if department is not None:
            filters = filters & Q(employee__department=department)

        employees_leave = EmployeeLeave.objects.filter(
            filters).prefetch_related('employee').order_by(
                "start_date", "employee__first_name").values(
                    "employee__first_name",
                    "employee__last_name",
                    "employee__id",
                    "employee__manager__first_name",
                    "employee__manager__last_name",
                    "start_date",
                    "has_deduction",
                    "leave_type__status_name",
                    "notes"
        ).distinct()

        return employees_leave


def get_date_range(request):
    """Return a list with the date range beteween two dates."""

    start_date = datetime.strptime(
        request.POST.get("start_date"), "%Y-%m-%d")
    end_date = datetime.strptime(request.POST.get("end_date"), "%Y-%m-%d")

    date_list = []
    for d in range((end_date - start_date).days + 1):
        date_formated = datetime.strftime(
            start_date + timedelta(days=d), "%d/%m/%y")
        date_list.append(date_formated)

    return date_list


@login_required
def draw_leaver_report(request):
    """Draw spreadsheet with leavers."""

    today = datetime.today()
    employees_leave = get_employee_leave(request)

    workbook = Workbook()
    worksheet = workbook.active
    worksheet.cell(row=3, column=1).value = "First Name"
    worksheet.cell(row=3, column=2).value = "Last Name"
    worksheet.cell(row=3, column=3).value = "Manager"
    worksheet.cell(row=3, column=4).value = "Leave Date"
    worksheet.cell(row=3, column=5).value = "Deduction"
    worksheet.cell(row=3, column=6).value = "Leave Type"
    worksheet.cell(row=3, column=7).value = "Comments"

    for i, employee_leave in enumerate(employees_leave, start=4):
        worksheet.cell(
            row=i, column=1).value = employee_leave["employee__first_name"]
        worksheet.cell(
            row=i, column=2).value = employee_leave["employee__last_name"]

        if employee_leave["employee__manager__first_name"] is None:
            worksheet.cell(
                row=i, column=3).value = "-"
        else:
            worksheet.cell(
                row=i, column=3
            ).value = (employee_leave['employee__manager__first_name'] +
                       " " + employee_leave['employee__manager__last_name'])

        worksheet.cell(row=i, column=4).value = datetime.strftime(
            employee_leave["start_date"], "%d/%m/%Y")

        if employee_leave["has_deduction"]:
            worksheet.cell(row=i, column=5).value = "Yes"
            for j in range(worksheet.min_column, worksheet.max_column + 1):
                worksheet.cell(row=i, column=j).font = Font(
                    color="F94144", bold=True)
        else:
            worksheet.cell(row=i, column=5).value = "No"

        worksheet.cell(
            row=i, column=6).value = employee_leave["leave_type__status_name"]

        worksheet.cell(row=i, column=7).value = employee_leave["notes"]

    config_header_styles(worksheet, 3, worksheet.max_column)
    config_employee_styles(worksheet)

    worksheet.column_dimensions[get_column_letter(
        worksheet.max_column)].width = 150
    worksheet.column_dimensions[get_column_letter(6)].width = 40

    output = HttpResponse(save_virtual_workbook(
        workbook), content_type='application/ms-excel')
    output['Content-Disposition'] = f'attachment; \
        filename=leaver_report_{datetime.strftime(today, "%d/%m/%y")}.xlsx'

    return output


@login_required
@user_passes_test(userHasAccess,
                  login_url="/dashboard/",
                  redirect_field_name=None)
def draw_attendance_report(request):
    """Draw a spreadsheet with the attendance report."""

    workbook = Workbook()
    worksheet = workbook.active

    today = datetime.today()
    employee_attendances = get_employee_attendances(request)
    employees = employee_attendances.order_by(
        "employee__first_name").values_list(
        "employee_id",
        "employee__first_name",
        "employee__last_name",
        "employee__manager__first_name",
        "employee__manager__last_name",
        "employee__employee_status"
    ).distinct()
    date_range = get_date_range(request)
    status = AttendanceStatus.objects.all()
    step = status.count()

    # Freeze panes for the headers/rows
    worksheet.freeze_panes = "C4"

    # Set the first col and row.
    last_col_num = 9
    first_row = 4

    # Set Headers
    worksheet.cell(row=3, column=1).value = "First Name"
    worksheet.cell(row=3, column=2).value = "Last Name"
    worksheet.cell(row=3, column=3).value = "Manager"
    worksheet.cell(row=3, column=4).value = "Active Total"
    worksheet.cell(row=3, column=5).value = "Inactive Total"
    worksheet.cell(row=3, column=6).value = "Holidays Total"
    worksheet.cell(row=3, column=7).value = "Bank Holidays Total"
    worksheet.cell(row=3, column=8).value = "Clawback Total"
    worksheet.cell(row=3, column=9).value = "Comments"

    config_header_styles(worksheet, 3, last_col_num)

    worksheet.column_dimensions[get_column_letter(9)].width = 50

    for employee in employees:
        employee_first_name = employee[1]
        employee_last_name = employee[2]
        employee_status = employee[5]
        manager_name = ""

        # Config and add employees name
        if employee_status == "Leaver":
            worksheet.cell(row=first_row, column=1).font = Font(color="F94144")
            worksheet.cell(row=first_row, column=2).font = Font(color="F94144")

reports/templates/reports/attendance_report.html
{% extends "base.html" %}{% load static %}{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-5 mb-5">
    <div class="row">
        <h1 class="pl-2">Attendance Report</h1>
        <div class="text-start">
            <a href="{% url 'reports:report_list' %}"><i class="fas fa-angle-left"></i> Back</a>
            <hr>
        </div>
    </div>
    <div class="container shadow-sm rounded p-4 bg-light">
        <form action="{% url 'reports:draw_attendance_report' %}" method="POST">
        {% csrf_token %}
            <div class="row">
                <div class="col-lg-2 col-sm-12">
                    {{form.start_date|as_crispy_field}}
                </div>
                <div class="col-lg-2 col-sm-12">
                    {{form.end_date|as_crispy_field}}
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3 col-sm-12">
                    {{form.employee|as_crispy_field}}
                </div>
                <div class="col-lg-2 col-sm-12">
                    {{form.department|as_crispy_field}}
                </div>
                <div class="col-lg-2 col-sm-12">
                    {{form.payroll_type|as_crispy_field}}
                </div>
            </div>
            <div class="text-end">
                <button type="submit" id="btnSubmit" class="btn btn-sm btn-success"><i class="fas fa-check-circle"></i> Generate Report</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

reports/templates/reports/leaver_report.html
{% extends "base.html" %}{% load static %}{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-5 mb-5">
    <div class="row">
        <h1 class="pl-2">Leaver Report</h1>
        <div class="text-start">
            <a href="{% url 'reports:report_list' %}"><i class="fas fa-angle-left"></i> Back</a>
            <hr>
        </div>
    </div>
    <div class="container shadow-sm rounded p-4 bg-light">
        <form action="{% url 'reports:draw_leaver_report' %}" method="POST">
        {% csrf_token %}
            <div class="row">
                <div class="col-lg-2 col-sm-12">
                    {{form.start_date|as_crispy_field}}
                </div>
                <div class="col-lg-2 col-sm-12">
                    {{form.end_date|as_crispy_field}}
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3 col-sm-12">
                    {{form.employee|as_crispy_field}}
                </div>
                <div class="col-lg-2 col-sm-12">
                    {{form.department|as_crispy_field}}
                </div>
            </div>
            <div class="text-end">
                <button type="submit" id="btnSubmit" class="btn btn-sm btn-success"><i class="fas fa-check-circle"></i> Generate Report</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

reports/templates/reports/report_list.html
{% extends "base.html" %}{% load static %}{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-5 mb-5">
    <div class="row">
        <h1 class="pl-2">Hub Reports</h1>
        <div class="text-start">
            <a href="{% url 'dashboard:dashboard' %}"><i class="fas fa-angle-left"></i> Back</a>
            <hr>
        </div>
    </div>
    <div class="container">
        <div class="row">
        {% for key, value in reports.items %}
            <div class="col-lg-3 col-sm-6">
                <a href="{% url value %}">
                    <div class="card shadow-sm">
                        <div class="card-body text-end text-white bg-gray hvr-grow">                   
                            <h5 class="card-title">{{key}}</h5>
                            <p><i class="fas fa-file-alt display-3 mt-2"></i></p>                           
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

   