apiTools/urls.py
from django.urls import path
from . import views

app_name = "apiTools"

urlpatterns = [
    path("dncApi/", views.dncApi, name="dncApi"),
    path("dncApiExportCSV/", views.dncApiExportCSV, name="dncApiExportCSV"),
    path("dncApiExportXLS/", views.dncApiExportXLS, name="dncApiExportXLS"),
]

employee_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from allauth.account.views import LoginView
from django.views import defaults


def pageNotFound(request):
    return defaults.page_not_found(request, None)


def serverError(request):
    return defaults.server_error(request)


urlpatterns = [
    path('admin/', admin.site.urls),
    path("employee/", include("employee.urls", namespace="employee")),
    path("inventory/", include("inventory.urls", namespace="inventory")),
    path("apiTools/", include("apiTools.urls", namespace="apiTools")),
    path("dashboard/", include("dashboard.urls", namespace="dashboard")),
    path("userRoles/", include("userRoles.urls", namespace="userRoles")),
    path("bgeForms/", include("bgeForms.urls", namespace="bgeForms")),
    path("iberForms/", include("iberForms.urls", namespace="iberForms")),
    path("pstForms/", include("pstForms.urls", namespace="pstForms")),
    path("pinergyForms/", include("pinergyForms.urls", namespace="pinergyForms")),
    path("reports/", include("reports.urls", namespace="reports")),
    path('accounts/', include('allauth.urls')),
    path("", LoginView.as_view(), name="login"),
    path("404/", pageNotFound),
    path("500/", serverError),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

reports/urls.py
from django.urls import path
from .views import (attendance_report,
                    report_list,
                    draw_attendance_report,
                    leaver_report,
                    draw_leaver_report)

app_name = "reports"

urlpatterns = [
    path("report_list/", report_list, name="report_list"),
    path("attendance_report/", attendance_report, name="attendance_report"),
    path("leaver_report/", leaver_report, name="leaver_report"),
    path("draw_attendance_report/", draw_attendance_report,
         name="draw_attendance_report"),
    path("draw_leaver_report/", draw_leaver_report,
         name="draw_leaver_report"),
]

apiTools/models.py
from django.db import models

# Create your models here.

apiTools/forms.py
from django import forms

tenants = (
    ("", ""),
    ("iber", "Iberdrola"),
    ("inm", "INM"),
    ("pin", "Pinergy"),
)


class DncApiForm(forms.Form):
    tenant = forms.ChoiceField(label="Tenants", choices=tenants, required=True)
    campaignID = forms.CharField(label="Campaign ID", required=True)
    customerContactNumber = forms.CharField(label="Customer Contact Numbers",
                                            required=True,
                                            help_text="You can input one \
                                     or more phone numbers separated by spaces.",
                                            widget=forms.Textarea(attrs={"rows": 2}))

apiTools/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from .forms import DncApiForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from datetime import datetime
from openpyxl import Workbook
from openpyxl.writer.excel import save_virtual_workbook
from openpyxl.styles import Font
import json
import xmltodict
import csv
import os
import requests

# ! Initialize the list to be used on the exports
responseMessage = []

# ! Gets the current system date to be used on the exports
today = datetime.now()


def userHasAccess(user):
    if user.department.department_name == "Technology":
        return True
    else:
        return False


@login_required
@user_passes_test(userHasAccess,
                  login_url="/dashboard/",
                  redirect_field_name=None)
def dncApi(request):
    """ Delete customer from campaign. """

    form = DncApiForm()

    responseMessage.clear()

    if request.method == "POST":

        form = DncApiForm(request.POST)

        if form.is_valid():

            campaignID = request.POST["campaignID"]
            customerList = list(request.POST["customerContactNumber"].split())
            tenant = request.POST["tenant"]
            apiKey = getApiKey(tenant)
            server = getServer(tenant)
            customerIDList = getCustomerByPhone(
                customerList, campaignID, tenant)

            for currentCustomer in customerIDList:

                url = f"{server}/api/tstats/campaigns/{campaignID}/customers/{currentCustomer}"

                payload = {}
                headers = {
                    'Authorization': apiKey
                }

                response = requests.request(
                    "DELETE", url, headers=headers, data=payload)

                if response.status_code == 401:
                    messages.warning(request, f"""
                    Status {response.status_code}
                        - Authentication Error.""")
                    break

                elif (response.status_code == 200 or
                      response.status_code == 204):

                    responseMessage.append(
                        {
                            "tenant": tenant,
                            "campaignID": campaignID,
                            "customerID": currentCustomer,
                            "status": response.status_code,
                            "message": f"Customer ID: {currentCustomer} deleted successfully.",
                            "date": today.strftime("%c")
                        })
                else:
                    messageParsed = json.loads(response.content)
                    messageParsed = messageParsed["message"]

                    responseMessage.append(
                        {
                            "tenant": tenant,
                            "campaignID": campaignID,
                            "customerID": currentCustomer,
                            "status": response.status_code,
                            "message": f"Customer ID: {currentCustomer} - {messageParsed}",
                            "date": today.strftime("%c")
                        })

    context = {
        "form": form,
        "responseMessage": responseMessage
    }

    return render(request, "apiTools/dncApi.html", context)


def getApiKey(tenant):
    """
        Return API key based on tenant.

        Required Arguments:
        tenant
    """

    if tenant == "iber":

        authKey = os.environ.get("IBERDROLA_API_KEY")

    elif tenant == "inm":

        authKey = os.environ.get("INM_API_KEY")

    elif tenant == "pin":

        authKey = os.environ.get("PINERGY_API_KEY")

    return authKey


def dncApiExportCSV(request):
    """ Exports current query to CSV file """
    campaignID = responseMessage[0]["campaignID"]
    response = HttpResponse(content_type="text/csv")
    response['Content-Disposition'] = f'attachment; \
        filename=dncReport_{campaignID}_{today.strftime("%x")}".csv"'

    if responseMessage:

        writer = csv.writer(response)
        writer.writerow(
            ["Tenant", "Campaign ID",
             "Customer ID", "Status", "Message", "Date"])

        for r in responseMessage:
            if r["tenant"]:
                r["tenant"] = getTenantName(r["tenant"])
            writer.writerow(
                r.values())

    return response


def dncApiExportXLS(request):
    """ Exports current query to XLS file """

    excelData = responseMessage
    wb = Workbook()
    ws = wb.active

    ws["A1"].value = "Tenant"
    ws["B1"].value = "Campaign ID"
    ws["C1"].value = "Customer ID"
    ws["D1"].value = "Status"
    ws["E1"].value = "Message"
    ws["F1"].value = "Date"

    for cell in ws["1:1"]:
        cell.font = Font(bold=True)

    row = 2
    for r in excelData:
        ws[f"A{row}"].value = getTenantName(r["tenant"])
        ws[f"B{row}"].value = r["campaignID"]
        ws[f"C{row}"].value = r["customerID"]
        ws[f"D{row}"].value = r["status"]
        ws[f"E{row}"].value = r["message"]
        ws[f"F{row}"].value = r["date"]
        row += 1

        response = HttpResponse(save_virtual_workbook(
            wb), content_type='application/vnd.ms-excel')
        response['Content-Disposition'] = f'attachment; \
            filename=dncReport_{r["campaignID"]}_{today.strftime("%x")}".xlsx"'

    return response


def getTenantName(tenant):
    """
    Returns correct tenant name.
    Required arguments: tenant
    """

    if tenant == "iber":
        tenant = "Iberdrola"
    elif tenant == "inm":
        tenant = "Independent News & Media"
    elif tenant == "pin":
        tenant = "Pinergy"

    return tenant


def getServer(tenant):
    """
    Returns correct server based on tenant passed.
    """

    if tenant == "iber":
        return "https://vcc-eu8.8x8.com"
    else:
        return "https://vcc-eu9.8x8.com"


def getCustomerByPhone(phoneList, campaignID, tenant):
    """
    Return customerID by phoneNumber provided.
    It receives a list of phone numbers.
    Required Argument: phoneList
    """

    customerList = []
    server = getServer(tenant)

    for phoneNumber in phoneList:
        url = f"{server}/api/stats/campaigns/{campaignID}/records?phone-list=*Contact%20Number%7C{phoneNumber}"

        payload = {}
        headers = {
            'Authorization': "Basic c2FsZXNzZW5zZWliMDE6ZDdiYmRmZGYyM2ZlY2M1ZDBiNDRlNjA1YmE2ZGZkNmMyMGZmZmRmMmYxZmUwMTQ1ZWU3ZmU4MzkzZGYxNjg1Ng=="
        }

        response = requests.request(
            "GET", url, headers=headers, data=payload)

        obj = xmltodict.parse(response.content)

        if not obj["records"] is None:
            customerList.append(obj["records"]["record"]["record-id"])
        else:
            customerList.append(phoneNumber)

    return customerList

apiTools/templates/apiTools/dncApi.html
{% extends "base.html" %}{% load static %}{% load crispy_forms_tags %}
{% block extraCss %}
<link rel="stylesheet" href="{% static 'apiTools/apiTools.css' %}">
{% endblock extraCss %}
{% block content %}
<div class="container mt-5 mb-5">
    <div class="row">
        <h1 class="pl-2">Do Not Call - API</h1>
        <p>Delete customers from an active campaign</p>
    </div>
    <hr>
    <div class="container shadow-sm rounded p-4 bg-light">
        <form action="{% url 'apiTools:dncApi' %}" method="POST">
        {% csrf_token %}
            <div class="row">
                <div class="col-4">
                    {{form.tenant|as_crispy_field}}
                </div>
                <div class="col-4">
                    {{form.campaignID|as_crispy_field}}
                </div>
                {% if responseMessage %}
                <div class="col-4 d-flex align-items-center mt-3 justify-content-end">
                    <a href="{% url 'apiTools:dncApiExportCSV' %}"class="btn btn-sm btn-warning m-1"><i class="fas fa-file-csv"></i> Export .CSV</a>
                    <a href="{% url 'apiTools:dncApiExportXLS' %}"class="btn btn-sm btn-warning m-1"><i class="far fa-file-excel"></i> Export .XLS</a>
                </div>
                {% endif %}
            </div>
            <div class="row">
                <div class="col-12">
                    {{form.customerContactNumber|as_crispy_field}}
                </div>
            </div>
            <div class="text-end mb-1 me-1">

            </div>
            <div class="text-end">
                <a href="{% url 'apiTools:dncApi' %}"class="btn btn-sm btn-secondary"><i class="fas fa-times-circle"></i> Clear</a>
                <button type="submit" id="btnSubmit" class="btn btn-sm btn-success"><i class="fas fa-check-circle"></i> Submit</button>
            </div>
        </form>
    </div>
    {% if responseMessage %}
    <div class="card mt-4 text-center shadow-sm">
        <div class="card-header">
            Query Result:
        </div>
        <div class="card-body">
            <h4 class="text-center"></h4>        
        {% if responseMessage|length > 8 %}
            <ul class="text-center p-0 grid-list">
        {% else %}
            <ul class="text-center p-0">
        {% endif %}
            {% for message in responseMessage %}
                {% if message.status == 200 or message.status == 204 %}
                    <li class="list-group-item list-group-item-success m-1">Status {{message.status}} - {{message.message}}</li>
                {% else %}
                    <li class="list-group-item list-group-item-danger m-1">Status {{message.status}} - {{message.message}}</li>
                {% endif %}
            {% endfor %}
            </ul>
            
            {% endif %}
        </div>
    </div>
</div>
{% endblock  %}