dashboard/urls.py
from django.urls import path
from .views import dashboard, getChartData

app_name = "dashboard"

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("chart/", getChartData.as_view(), name="getChartData"),
]

employee/urls.py
from django.urls import path
from .views import (
    employeeList,
    employeeDetail,
    employeeCreate,
    employeeUpdate,
    employeeDelete,
    employeeAddLeave,
    employeeAddAttendance,
    employeeJobHistory,
    updateTeamAttendance,
    employeeUploadDocument,
    deleteAttendance,
    update_carry_over_holidays
)

app_name = "employee"

urlpatterns = [
    path("", employeeList, name="employeeList"),
    path("<int:pk>/", employeeDetail, name="employeeDetail"),
    path("create/", employeeCreate, name="employeeCreate"),
    path("<int:pk>/update/", employeeUpdate, name="employeeUpdate"),
    path("<int:pk>/delete/", employeeDelete, name="employeeDelete"),
    path("<int:pk>/leave/", employeeAddLeave, name="employeeAddLeave"),
    path(
        "<int:pk>/jobHistory/",
        employeeJobHistory,
        name="employeeJobHistory"
    ),
    path(
        "<int:pk>/document/",
        employeeUploadDocument,
        name="employeeUploadDocument"
    ),
    path("<int:pk>/attendance/", employeeAddAttendance,
         name="employeeAddAttendance"),
    path("<int:pk>/deleteAttendance/", deleteAttendance,
         name="deleteAttendance"),
    path("attendance/", updateTeamAttendance,
         name="updateTeamAttendance"),
    path("<int:pk>/update_carry_over_holidays/", update_carry_over_holidays,
         name="update_carry_over_holidays"),
]

employee_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from allauth.account.views import LoginView
from django.views import defaults


def pageNotFound(request):
    return defaults.page_not_found(request, None)


def serverError(request):
    return defaults.server_error(request)


urlpatterns = [
    path('admin/', admin.site.urls),
    path("employee/", include("employee.urls", namespace="employee")),
    path("inventory/", include("inventory.urls", namespace="inventory")),
    path("apiTools/", include("apiTools.urls", namespace="apiTools")),
    path("dashboard/", include("dashboard.urls", namespace="dashboard")),
    path("userRoles/", include("userRoles.urls", namespace="userRoles")),
    path("bgeForms/", include("bgeForms.urls", namespace="bgeForms")),
    path("iberForms/", include("iberForms.urls", namespace="iberForms")),
    path("pstForms/", include("pstForms.urls", namespace="pstForms")),
    path("pinergyForms/", include("pinergyForms.urls", namespace="pinergyForms")),
    path("reports/", include("reports.urls", namespace="reports")),
    path('accounts/', include('allauth.urls')),
    path("", LoginView.as_view(), name="login"),
    path("404/", pageNotFound),
    path("500/", serverError),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

reports/urls.py
from django.urls import path
from .views import (attendance_report,
                    report_list,
                    draw_attendance_report,
                    leaver_report,
                    draw_leaver_report)

app_name = "reports"

urlpatterns = [
    path("report_list/", report_list, name="report_list"),
    path("attendance_report/", attendance_report, name="attendance_report"),
    path("leaver_report/", leaver_report, name="leaver_report"),
    path("draw_attendance_report/", draw_attendance_report,
         name="draw_attendance_report"),
    path("draw_leaver_report/", draw_leaver_report,
         name="draw_leaver_report"),
]

employee/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import (
    Employee,
    EmployeeDocuments,
    EmployeeHolidays,
    EmployeeLeave,
    EmployeeAttendance,
    EmployeeJobHistory
)
from .forms import (
    EmployeeModelForm,
    EmployeeLeaveInlineForm,
    EmployeeJobHistoryInlineForm,
    EmployeeAttendanceInlineForm,
    EmployeeDocumentInlineForm,
    EmployeeHolidaysForm,
)
from inventory.models import Phone, Tablet, SIM, OtherDevice
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.paginator import Paginator
from django.db.models import Q
from django.db.models import Value as V
from django.db.models.functions import Concat
from django.contrib import messages
from userRoles.views import getUserType, getSeniorManager
from userAccounts.models import CustomUser
import datetime
import math


def userHasAccess(user):

    if (getUserType(user) == "HR" or
            getUserType(user) == "manager" or
            user.is_superuser):
        return True
    else:
        return False


@login_required
@user_passes_test(userHasAccess,
                  login_url="/dashboard/",
                  redirect_field_name=None)
def employeeList(request):
    """ Renders a paginated list of all employees. """

    searchQuery = request.GET.get("searchEmployee", None)
    managerList = CustomUser.objects.filter(
        is_manager="Y").order_by("username")

    if searchQuery and searchQuery.isdigit():
        employees = Employee.objects.annotate(
            full_name=Concat('first_name', V(' '), 'last_name')
        ).filter(
            Q(full_name__icontains=searchQuery) |
            Q(last_name__icontains=searchQuery) |
            Q(first_name__icontains=searchQuery) |
            Q(work_email__icontains=searchQuery) |
            Q(role__role_name__icontains=searchQuery) |
            Q(department__department_name__icontains=searchQuery) |
            Q(sub_department__sub_department_name__icontains=searchQuery) |
            Q(employee_status__icontains=searchQuery) |
            Q(manager=searchQuery)
        ).order_by("first_name")

    elif searchQuery and not searchQuery.isdigit():
        employees = Employee.objects.annotate(
            full_name=Concat('first_name', V(' '), 'last_name')
        ).filter(
            Q(full_name__icontains=searchQuery) |
            Q(last_name__icontains=searchQuery) |
            Q(first_name__icontains=searchQuery) |
            Q(work_email__icontains=searchQuery) |
            Q(role__role_name__icontains=searchQuery) |
            Q(department__department_name__icontains=searchQuery) |
            Q(sub_department__sub_department_name__icontains=searchQuery) |
            Q(employee_status__icontains=searchQuery)
        ).order_by("first_name")

    else:
        employees = Employee.objects.all().order_by("first_name")

    if getUserType(request.user) == "manager" and not (
            getUserType(request.user) == "HR" or
            getSeniorManager(request.user) == "SFSM" or
            getSeniorManager(request.user) == "OPM" or
            getSeniorManager(request.user) == "ACD"):
        employees = employees.filter(
            manager=request.user
        ).exclude(
            employee_status="Leaver"
        )

    elif getSeniorManager(request.user) == "OPM":
        employees = employees.filter(
            department=request.user.department,
        ).exclude(
            employee_status="Leaver"
        )

    elif getSeniorManager(request.user) == "SFSM":
        employees = employees.filter(
            department=request.user.department,
            sub_department=request.user.sub_department
        ).exclude(
            employee_status="Leaver"
        )

    elif getSeniorManager(request.user) == "ACD":
        employees = employees.filter(
            department=request.user.department,
        ).exclude(
            employee_status="Leaver"
        )

    # Gives a list per page of 10 employees
    employeePaginator = Paginator(employees, 10)

    pageNum = (request.GET.get("page"))

    page = employeePaginator.get_page(pageNum)

    context = {
        "page": page,
        "managerList": managerList
    }

    return render(request, "employee/employeeList.html", context)


@ login_required
@ user_passes_test(userHasAccess,
                   login_url="/dashboard/",
                   redirect_field_name=None)
def employeeDetail(request, pk):
    """ Render employee details based on the PK/ID provided. """

    employee = get_object_or_404(Employee, id=pk)
    leaveList = EmployeeLeave.objects.filter(employee=employee)
    attendanceList = EmployeeAttendance.objects.filter(
        employee=employee).order_by("-attendance_date")[:60:-1]
    jobHistory = EmployeeJobHistory.objects.filter(employee=employee)
    documents = EmployeeDocuments.objects.filter(employee=employee)
    form = EmployeeModelForm(instance=employee)

    phones = Phone.objects.all().filter(assigned_to=pk)
    tablets = Tablet.objects.all().filter(assigned_to=pk)
    sims = SIM.objects.all().filter(assigned_to=pk)
    other_devices = OtherDevice.objects.all().filter(assigned_to=pk)

    annual_leave = calculate_annual_leave(employee)
    carry_over_holidays = EmployeeHolidays.objects.filter(
        employee=employee).first()

    holidays_form = EmployeeHolidaysForm(instance=carry_over_holidays)

    context = {
        "employee": employee,
        "leaveList": leaveList,
        "attendanceList": attendanceList,
        "jobHistory": jobHistory,
        "documents": documents,
        "form": form,
        "phones": phones,
        "tablets": tablets,
        "sims": sims,
        "other_devices": other_devices,
        "annual_leave": annual_leave,
        "holidays_form": holidays_form
    }
    return render(request, "employee/employeeDetail.html", context)


@ login_required
@ user_passes_test(userHasAccess,
                   login_url="/dashboard/",
                   redirect_field_name=None)
def employeeAddLeave(request, pk):
    """ Handles add/edit employee leave based on the PK/ID provided. """

    employee = get_object_or_404(Employee, id=pk)
    inlineForm = EmployeeLeaveInlineForm(instance=employee)

    # If request is POST, populate the inline form,
    # validates the form and save.
    if request.method == "POST":
        inlineForm = EmployeeLeaveInlineForm(request.POST, instance=employee)

        if inlineForm.is_valid():
            inlineForm.save()
            messages.success(request, "Employee leave updated successfully.")

            return redirect(f"/employee/{pk}")

        else:
            messages.error(request, "Error updating employee leave.")

    context = {
        "inlineForm": inlineForm,
        "employee": employee
    }
    return render(request, "employee/employeeLeave.html", context)


@ login_required
@ user_passes_test(userHasAccess,
                   login_url="/dashboard/",
                   redirect_field_name=None)
def employeeCreate(request):
    """
         Renders a new employee form and
         creates a new employee if form validation passes.
    """

    form = EmployeeModelForm()

    # If request is POST, validates the form and save.
    if request.method == "POST":

        form = EmployeeModelForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, "Employee created successfully.")

            return redirect("/employee")
        else:
            messages.error(request, form.errors)

    context = {
        "form": form
    }

    return render(request, "employee/employeeCreate.html", context)


@ login_required
@ user_passes_test(userHasAccess,
                   login_url="/dashboard/",
                   redirect_field_name=None)
def employeeUpdate(request, pk):
    """ Update an existing employee """

    employee = get_object_or_404(Employee, id=pk)
    form = EmployeeModelForm(instance=employee)
    carry_over_holidays = EmployeeHolidays.objects.filter(
        employee=employee).first()
    holidays_form = EmployeeHolidaysForm(instance=carry_over_holidays)
    annual_leave = calculate_annual_leave(employee)

    if request.method == "POST":

        form = EmployeeModelForm(request.POST, instance=employee)

        if form.is_valid():
            form.save()
            messages.success(request, "Employee updated successfully.")
            return redirect(f"/employee/{employee.id}")
        else:
            messages.error(
                request,
                ("Something went wrong. If the problem "
                 "persists contact support.")
            )

    context = {
        "employee": employee,
        "form": form,
        "annual_leave": annual_leave,
        "holidays_form": holidays_form,
        "carry_over_holidays": carry_over_holidays
    }

    return render(request, "employee/employeeUpdate.html", context)


@ login_required
@ user_passes_test(userHasAccess,
                   login_url="/dashboard/",
                   redirect_field_name=None)
def employeeDelete(request, pk):
    """ Delete an existing employee """

    try:
        employee = get_object_or_404(Employee, id=pk)
        employee.delete()
        messages.success(request, "Employee deleted successfully.")

    except Exception:
        messages.error(
            request,
            ("Sorry, something went wrong. "
             "If the problem persists contact support.")
        )

    finally:

        return redirect("/employee")


@ login_required
@ user_passes_test(userHasAccess,
                   login_url="/dashboard/",
                   redirect_field_name=None)
def employeeAddAttendance(request, pk):
    """ Handles Edit/Add attendance based on the PK/ID provided. """

    employee = get_object_or_404(Employee, id=pk)
    inlineForm = EmployeeAttendanceInlineForm(instance=employee)
    # If request is POST, populate the inline form,

employee/templates/employee/EmployeeDocuments.html
{% extends "base.html" %} {% block content %} {% load crispy_forms_tags %}
<div class="container mt-5 mb-5">
    <h1 class="ms-2">Edit Documents</h1>
    <div class="text-start ms-2">
        <a href="{% url 'employee:employeeDetail' pk=employee.id %}"><i class="fas fa-angle-left"></i> Back to Employee</a>
    </div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% comment %} Documents {% endcomment %}
        {% include "../employee/includes/employeeDocumentsForm.html" with isEditable="true"%}
 
        <div class="text-end mt-3">
            <button type="reset" class="btn btn-sm btn-secondary">Clear</button>
            <button type="submit" class="btn btn-sm btn-success">Submit</button>
        </div>
    </form>
</div>
{% endblock %}

employee/templates/employee/EmployeeLeave.html
{% extends "base.html" %} {% block content %} {% load crispy_forms_tags %}
<div class="container mt-5 mb-5">
    <h1 class="ms-2">Edit Employee Leave</h1>
    <div class="text-start ms-2">
        <a href="{% url 'employee:employeeDetail' pk=employee.id %}"><i class="fas fa-angle-left"></i> Back to Employee</a>
    </div>
    <form method="post">
        {% csrf_token %}
        {% comment %} Leave Details {% endcomment %}
        {% include "../employee/includes/employeeLeaveForm.html" with isEditable="true"%}
 
        <div class="text-end mt-3">
            <button type="reset" class="btn btn-sm btn-secondary">Clear</button>
            <button type="submit" class="btn btn-sm btn-success">Submit</button>
        </div>
    </form>
</div>
{% endblock %}

employee/templates/employee/employeeAttendance.html
{% extends "base.html" %} {% block content %} {% load crispy_forms_tags %}
<div class="container mt-5 mb-5">
  <h1 class="ms-2">{{employee}}'s Attendance</h1>
    <div class="text-start ms-2">
        <a href="{% url 'employee:employeeDetail' pk=employee.id %}"><i class="fas fa-angle-left"></i> Back to Employee</a>
    </div>
    <form method="post">
        {% csrf_token %}

        {% comment %} Attendance Details {% endcomment %}
        {% include "../employee/includes/employeeAttendanceForm.html" with isEditable="true"%}
        
        <div class="text-end mt-3">
            <button type="reset" class="btn btn-sm btn-secondary">Clear</button>
            <button type="submit" class="btn btn-sm btn-success">Submit</button>
        </div>
    </form>
</div>
{% endblock %}

employee/templates/employee/employeeCreate.html
{% extends "base.html" %} {% block content %} {% load crispy_forms_tags %}
<div class="container mt-5 mb-5">
  <h1 class="ms-2">Add New Employee</h1>
  <div class="text-start ms-2">
    <a href="{% url 'employee:employeeList' %}"><i class="fas fa-angle-left"></i> Back to Employee List</a>
  </div>
  <form method="POST">
    {% csrf_token %} 
    {% comment %} Personal Details {% endcomment %}
    {% include "../employee/includes/employeePersonalDetails.html" with isEditable="true" %}
    {% comment %} Job Details {% endcomment %}
    {% include "../employee/includes/employeeJobDetails.html" with isEditable="true" %}
    
    <div class="text-end mt-3 pe-2">
      <button type="reset" class="btn btn-sm btn-secondary">Clear</button>
      <button type="submit" class="btn btn-sm btn-success">Submit</button>
    </div>
  </form>
</div>
{% endblock content %}

employee/templates/employee/employeeDetail.html
{% extends "base.html" %} {% block content %} {% load crispy_forms_tags %}
<div class="container mt-5 mb-5">
  <h1 class="ms-2">{{employee.first_name}} {{employee.last_name}} - Employee Details</h1>
  <form action="POST">
    {% csrf_token %} 
    <div class="row align-items-center">
      <div class="col text-start ms-2">
        <a href="{% url 'employee:employeeList' %}"><i class="fas fa-angle-left"></i> Back to Employees List</a>
      </div>
    {% if user.department.department_name == "HR" or user.department.department_name == "Management" or user.department.department_name == "Accounts" or user.is_superuser %}
      <div class="col text-end">
        <a
          href="{% url 'employee:employeeUpdate' pk=employee.pk %}"
          class="btn btn-sm btn-warning me-2"
          ><i class="fas fa-edit"></i> Edit Employee</a
        >
      </div>
    </div>

    {% comment %} Personal Details {% endcomment %}
    {% include "../employee/includes/employeePersonalDetails.html" with isEditable="false" %}
    
    {% comment %} Job Details {% endcomment %}
    {% include "../employee/includes/employeeJobDetails.html" with isEditable="false" %}

    {% comment %} Attendance Details {% endcomment %}
    {% include "../employee/includes/employeeAttendanceDetails.html" with isEditable="false" %}

    {% comment %} Assets {% endcomment %}
    {% include "../employee/includes/employeeAssets.html" %}

    {% else %}

    {% comment %} Personal Details {% endcomment %}
    {% include "../employee/includes/employeePersonalDetails.html" with isEditable="false" %}

    {% comment %} Attendance Details {% endcomment %}
    {% include "../employee/includes/employeeAttendanceDetails.html" with isEditable="false" %}
    
    {% endif %}
    
  </form>
</div>
{% endblock content %}

employee/templates/employee/employeeJobHistory.html
{% extends "base.html" %} {% block content %} {% load crispy_forms_tags %}
<div class="container mt-5 mb-5">
  <h1 class="ms-2">Employee Job History</h1>
    <div class="text-start ms-2">
        <a href="{% url 'employee:employeeDetail' pk=employee.id %}"><i class="fas fa-angle-left"></i> Back to Employee</a>
    </div>
    <form method="post">
        {% csrf_token %}

        {% comment %} Job History Form {% endcomment %}
        {% include "../employee/includes/employeeJobHistoryForm.html" with isEditable="true"%}
        
        <div class="text-end mt-3">
            <button type="reset" class="btn btn-sm btn-secondary">Clear</button>
            <button type="submit" class="btn btn-sm btn-success">Submit</button>
        </div>
    </form>
</div>
{% endblock %}

employee/templates/employee/employeeList.html
{% extends "base.html" %} {% block content %}
<div class="container-fluid mt-5" id="container-employee-list">
    <div class="row mb-2">
    {% if user.department.department_name == "HR" or user.department.department_name == "Management" or user.department.department_name == "Accounts" %}
        <h1>Employees</h1>
    {% else %}
        <h1>My Team</h1>
    {% endif %}
    </div>
    {% if user.department.department_name == "HR" or user.department.department_name == "Management" or user.department.department_name == "Accounts" %}
    <div class="text-center">
      <hr class="mb-2">
      {% for manager in managerList %}
        <a href="{% url 'employee:employeeList' %}?searchEmployee={{manager.id}}" class="btn btn-sm btn-outline-secondary rounded-pill m-1">{{manager}}</a>
      {% endfor %}
        <hr class="mb-2 mt-2">
    </div>
    {% endif %}
  <div class="row pb-2">
    <div class="col-auto">
      <form action="{% url 'employee:employeeList' %}">
        <div class="input-group">
          <input
            name="searchEmployee"
            id="searchEmployee"
            type="text"
            class="form-control"
            placeholder="Search"
            aria-label="Search"
            aria-describedby="search-addon"
          />
          <button type="submit" class="btn btn-success"><i class="fas fa-search"></i></button>
          <a class="btn btn-danger" href="{% url 'employee:employeeList' %}"><i class="fas fa-times-circle"></i></a>
        </div>
      </form>
    </div>
    {% if user.department.department_name == "HR" or user.department.department_name == "Management" or user.is_superuser %}
      <div class="col-auto ms-auto mt-3">
        <a
          href="{% url 'employee:employeeCreate' %}"
          class="btn btn-sm btn-success"
          ><i class="fas fa-user-plus"></i> Add new employee</a
        >
      </div>
    {% endif %}
  </div>
  {% if page.object_list|length == 0 %}
  <hr>
  <div class="text-center">
    <strong><p>We didn't find any employees with this filter.</p></strong>
    <p>Clear search to see your employees.</p>
  </div>
    
  {% else %}
  <table id="tableEmployees" class="table table-hover table align-middle mt-2">
    <thead>
      <tr class="bg-light">
        <th scope="col">Employee</th>
        <th scope="col">Role</th>
        <th scope="col">Account/Dept</th>
        <th scope="col">Sub-Department</th>
        <th class="text-center" scope="col">Status</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% for employee in page.object_list %}
      <tr>
        <td class="small"><i class="fas fa-user text-secondary"></i> {{employee}}</td>
        <td class="small">{{employee.role}}</td>
        <td class="small">{{employee.department}}</td>
        <td class="small">{{employee.sub_department}}</td>
        {% comment %} Badges for different status {% endcomment %}
        {% include "../employee/includes/employeeStatusBadges.html" %}
        <td class="text-end">
          <a
            href="tel:{{employee.work_phone}}"
            class="btn btn-sm btn-success"
            ><i class="fas fa-phone"></i></a
          >
          <a
            href="mailto:{{employee.work_email}}"
            class="btn btn-sm btn-warning"
            ><i class="far fa-envelope text-white"></i></a
          >
          <a
            href="{% url 'employee:employeeDetail' pk=employee.pk %}"
            class="btn btn-sm btn-info"
            >Details</a
          >
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <nav aria-label="Page navigation">
    <ul class="pagination pagination-sm justify-content-end">
    {% if page.has_previous %}
      <li class="page-item">
        <a class="page-link" href="{% url 'employee:employeeList' %}?page={{ page.previous_page_number}}{% if request.GET.searchEmployee %}&searchEmployee={{ request.GET.searchEmployee }}{% endif %}"><i class="fas fa-angle-left"></i> Previous Page</a>
      </li>
    {% else %}
      <li class="page-item disabled">
          <a class="page-link" href="#" aria-disabled="true"><i class="fas fa-angle-left"></i> Previous Page</a>
      </li>
    {% endif %}
    {% if page.has_next %}
      <li class="page-item">
        <a class="page-link" href="{% url 'employee:employeeList' %}?page={{ page.next_page_number}}{% if request.GET.searchEmployee %}&searchEmployee={{ request.GET.searchEmployee }}{% endif %}">Next Page <i class="fas fa-angle-right"></i></a>
      </li>
    {% else %}
      <li class="page-item disabled">
          <a class="page-link" href="#" aria-disabled="true">Next Page <i class="fas fa-angle-right"></i></a>
      </li>
    {% endif %}
    </ul>
  </nav>
  {% endif %}
</div>
{% endblock content %}

employee/templates/employee/employeeUpdate.html
{% extends "base.html" %} {% block content %} {% load crispy_forms_tags %}
<div class="container mt-5 mb-5">
  <h1 class="ms-2">Edit Employee</h1>
  <div class="text-start ms-2">
    <a href="{% url 'employee:employeeDetail' pk=employee.id %}"><i class="fas fa-angle-left"></i> Back to Employee</a>
  </div>
  <form method="POST">
    {% csrf_token %}
    {% comment %} Personal Details {% endcomment %}
    {% include "../employee/includes/employeePersonalDetails.html" with isEditable="true" %}

    {% comment %} Job Details {% endcomment %}
    {% include "../employee/includes/employeeJobDetails.html" with isEditable="true" %}
    
    <div class="text-end p-2">
      <a
        href="{% url 'employee:employeeDelete' pk=employee.pk %}"
        class="btn btn-sm btn-danger"
        onclick="return confirm('Are you sure you want to delete this employee? This is irreversible');"
        >Delete</a
      >
      <button type="reset" class="btn btn-sm btn-secondary">Cancel</button>
      <button type="submit" class="btn btn-sm btn-warning">Update</button>
    </div>
  </form>
</div>
{% endblock content %}

employee/templates/employee/updateTeamAttendance.html
{% extends "base.html" %} {% block content %} {% load crispy_forms_tags %}
<div class="container mt-5 mb-5">
    <h1 class="ms-2">Change Team Attendance</h1>
    <div class="text-start ms-2">
        <a href="{% url 'dashboard:dashboard' %}"><i class="fas fa-angle-left"></i> Back to Dashboard</a>
    </div>
    <hr>
    <div class="container shadow-sm rounded p-4 bg-light">
        <form action="{% url 'employee:updateTeamAttendance' %}" method="POST">
        {% csrf_token %}
        {{inlineForm.management_form}}
            {% for form in inlineForm %}
            <div class="row">
                <div class="col-sm-12 col-lg-2 mb-2">
                {{ form.attendance_date|as_crispy_field }}
                </div>
                <div class="col-sm-12 col-lg-2 mb-2">
                {{ form.status|as_crispy_field }}
                </div>
                <div class="col-sm-12 col-lg-1 mb-2">
                {{ form.hours_worked|as_crispy_field }}
                </div>
                <div class="col-sm-12 col-lg-2 mb-2">
                {{ form.additional_status|as_crispy_field }}
                </div>
                <div class="col-sm-12 col-lg-3 mb-2">
                {{ form.additional_hours_worked|as_crispy_field }}
                </div>
                <div class="col-sm-12 col-lg-2 mb-2">
                {{ form.overtime_hours|as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                {{ form.notes|as_crispy_field }}
                </div>
            </div>
            {% endfor %}
            <p class="text-center text-muted fst-italic small">Team Attendance only updates members with status ACTIVE or BANK HOLIDAY</p>
            <div class="text-end mt-3">
                <button type="reset" class="btn btn-sm btn-secondary"><i class="fas fa-times-circle"></i> Clear</button>
                <button type="submit" id="btnSubmit" class="btn btn-sm btn-success"><i class="fas fa-check-circle"></i> Submit</button>
            </div>
        </form>
    </div>
    <div class="container mt-5">
        <h3>Change Individual Attendance</h3>
        <hr>
        <div class="row">
        {% for emp in attendanceList %}
            <div class="col col-sm-4 col-lg-3 col-xl-2">
                <a href="{% url 'employee:employeeAddAttendance' pk=emp.employee.pk %}" target="_blank">
                    <div class="card shadow-sm mb-4">
                    {% if emp.employee.employee_status == "Active" %}
                        <div class="card-body text-center text-white bg-green hvr-grow"> 
                        {% else %}
                        <div class="card-body text-center text-white bg-red hvr-grow">
                        {% endif %}                  
                            <h5 class="card-title text-truncate pb-1">{{emp}}</h5>
                            <hr class="m-1">
                            <p class="text-center m-0">Last Attendance:</p>
                            <p class="text-center m-0 fs-5">{{emp.attendance_date}}</p>
                            <hr class="m-1">
                            <p class="text-center m-0 fs-5"><strong>{{emp.employee.employee_status}}</strong></p>                         
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}