employee/urls.py
from django.urls import path
from .views import (
    employeeList,
    employeeDetail,
    employeeCreate,
    employeeUpdate,
    employeeDelete,
    employeeAddLeave,
    employeeAddAttendance,
    employeeJobHistory,
    updateTeamAttendance,
    employeeUploadDocument,
    deleteAttendance,
    update_carry_over_holidays
)

app_name = "employee"

urlpatterns = [
    path("", employeeList, name="employeeList"),
    path("<int:pk>/", employeeDetail, name="employeeDetail"),
    path("create/", employeeCreate, name="employeeCreate"),
    path("<int:pk>/update/", employeeUpdate, name="employeeUpdate"),
    path("<int:pk>/delete/", employeeDelete, name="employeeDelete"),
    path("<int:pk>/leave/", employeeAddLeave, name="employeeAddLeave"),
    path(
        "<int:pk>/jobHistory/",
        employeeJobHistory,
        name="employeeJobHistory"
    ),
    path(
        "<int:pk>/document/",
        employeeUploadDocument,
        name="employeeUploadDocument"
    ),
    path("<int:pk>/attendance/", employeeAddAttendance,
         name="employeeAddAttendance"),
    path("<int:pk>/deleteAttendance/", deleteAttendance,
         name="deleteAttendance"),
    path("attendance/", updateTeamAttendance,
         name="updateTeamAttendance"),
    path("<int:pk>/update_carry_over_holidays/", update_carry_over_holidays,
         name="update_carry_over_holidays"),
]

employee_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from allauth.account.views import LoginView
from django.views import defaults


def pageNotFound(request):
    return defaults.page_not_found(request, None)


def serverError(request):
    return defaults.server_error(request)


urlpatterns = [
    path('admin/', admin.site.urls),
    path("employee/", include("employee.urls", namespace="employee")),
    path("inventory/", include("inventory.urls", namespace="inventory")),
    path("apiTools/", include("apiTools.urls", namespace="apiTools")),
    path("dashboard/", include("dashboard.urls", namespace="dashboard")),
    path("userRoles/", include("userRoles.urls", namespace="userRoles")),
    path("bgeForms/", include("bgeForms.urls", namespace="bgeForms")),
    path("iberForms/", include("iberForms.urls", namespace="iberForms")),
    path("pstForms/", include("pstForms.urls", namespace="pstForms")),
    path("pinergyForms/", include("pinergyForms.urls", namespace="pinergyForms")),
    path("reports/", include("reports.urls", namespace="reports")),
    path('accounts/', include('allauth.urls')),
    path("", LoginView.as_view(), name="login"),
    path("404/", pageNotFound),
    path("500/", serverError),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.urls import path
from .views import (inventory_list, device_type_list,
                    add_new_device, edit_device, delete_device)


app_name = "inventory"

urlpatterns = [
    path('inventory_list/', inventory_list, name='inventory_list'),
    path('device_type_list/', device_type_list, name='device_type_list'),
    path('add_new_device/', add_new_device, name='add_new_device'),
    path('<int:id>/<str:device_type>/edit_device/',
         edit_device, name='edit_device'),
    path('<int:id>/<str:device_type>/delete_device/',
         delete_device, name='delete_device'),
]

reports/urls.py
from django.urls import path
from .views import (attendance_report,
                    report_list,
                    draw_attendance_report,
                    leaver_report,
                    draw_leaver_report)

app_name = "reports"

urlpatterns = [
    path("report_list/", report_list, name="report_list"),
    path("attendance_report/", attendance_report, name="attendance_report"),
    path("leaver_report/", leaver_report, name="leaver_report"),
    path("draw_attendance_report/", draw_attendance_report,
         name="draw_attendance_report"),
    path("draw_leaver_report/", draw_leaver_report,
         name="draw_leaver_report"),
]

employee/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import (
    Employee,
    EmployeeDocuments,
    EmployeeHolidays,
    EmployeeLeave,
    EmployeeAttendance,
    EmployeeJobHistory
)
from .forms import (
    EmployeeModelForm,
    EmployeeLeaveInlineForm,
    EmployeeJobHistoryInlineForm,
    EmployeeAttendanceInlineForm,
    EmployeeDocumentInlineForm,
    EmployeeHolidaysForm,
)
from inventory.models import Phone, Tablet, SIM, OtherDevice
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.paginator import Paginator
from django.db.models import Q
from django.db.models import Value as V
from django.db.models.functions import Concat
from django.contrib import messages
from userRoles.views import getUserType, getSeniorManager
from userAccounts.models import CustomUser
import datetime
import math


def userHasAccess(user):

    if (getUserType(user) == "HR" or
            getUserType(user) == "manager" or
            user.is_superuser):
        return True
    else:
        return False


@login_required
@user_passes_test(userHasAccess,
                  login_url="/dashboard/",
                  redirect_field_name=None)
def employeeList(request):
    """ Renders a paginated list of all employees. """

    searchQuery = request.GET.get("searchEmployee", None)
    managerList = CustomUser.objects.filter(
        is_manager="Y").order_by("username")

    if searchQuery and searchQuery.isdigit():
        employees = Employee.objects.annotate(
            full_name=Concat('first_name', V(' '), 'last_name')
        ).filter(
            Q(full_name__icontains=searchQuery) |
            Q(last_name__icontains=searchQuery) |
            Q(first_name__icontains=searchQuery) |
            Q(work_email__icontains=searchQuery) |
            Q(role__role_name__icontains=searchQuery) |
            Q(department__department_name__icontains=searchQuery) |
            Q(sub_department__sub_department_name__icontains=searchQuery) |
            Q(employee_status__icontains=searchQuery) |
            Q(manager=searchQuery)
        ).order_by("first_name")

    elif searchQuery and not searchQuery.isdigit():
        employees = Employee.objects.annotate(
            full_name=Concat('first_name', V(' '), 'last_name')
        ).filter(
            Q(full_name__icontains=searchQuery) |
            Q(last_name__icontains=searchQuery) |
            Q(first_name__icontains=searchQuery) |
            Q(work_email__icontains=searchQuery) |
            Q(role__role_name__icontains=searchQuery) |
            Q(department__department_name__icontains=searchQuery) |
            Q(sub_department__sub_department_name__icontains=searchQuery) |
            Q(employee_status__icontains=searchQuery)
        ).order_by("first_name")

    else:
        employees = Employee.objects.all().order_by("first_name")

    if getUserType(request.user) == "manager" and not (
            getUserType(request.user) == "HR" or
            getSeniorManager(request.user) == "SFSM" or
            getSeniorManager(request.user) == "OPM" or
            getSeniorManager(request.user) == "ACD"):
        employees = employees.filter(
            manager=request.user
        ).exclude(
            employee_status="Leaver"
        )

    elif getSeniorManager(request.user) == "OPM":
        employees = employees.filter(
            department=request.user.department,
        ).exclude(
            employee_status="Leaver"
        )

    elif getSeniorManager(request.user) == "SFSM":
        employees = employees.filter(
            department=request.user.department,
            sub_department=request.user.sub_department
        ).exclude(
            employee_status="Leaver"
        )

    elif getSeniorManager(request.user) == "ACD":
        employees = employees.filter(
            department=request.user.department,
        ).exclude(
            employee_status="Leaver"
        )

    # Gives a list per page of 10 employees
    employeePaginator = Paginator(employees, 10)

    pageNum = (request.GET.get("page"))

    page = employeePaginator.get_page(pageNum)

    context = {
        "page": page,
        "managerList": managerList
    }

    return render(request, "employee/employeeList.html", context)


@ login_required
@ user_passes_test(userHasAccess,
                   login_url="/dashboard/",
                   redirect_field_name=None)
def employeeDetail(request, pk):
    """ Render employee details based on the PK/ID provided. """

    employee = get_object_or_404(Employee, id=pk)
    leaveList = EmployeeLeave.objects.filter(employee=employee)
    attendanceList = EmployeeAttendance.objects.filter(
        employee=employee).order_by("-attendance_date")[:60:-1]
    jobHistory = EmployeeJobHistory.objects.filter(employee=employee)
    documents = EmployeeDocuments.objects.filter(employee=employee)
    form = EmployeeModelForm(instance=employee)

    phones = Phone.objects.all().filter(assigned_to=pk)
    tablets = Tablet.objects.all().filter(assigned_to=pk)
    sims = SIM.objects.all().filter(assigned_to=pk)
    other_devices = OtherDevice.objects.all().filter(assigned_to=pk)

    annual_leave = calculate_annual_leave(employee)
    carry_over_holidays = EmployeeHolidays.objects.filter(
        employee=employee).first()

    holidays_form = EmployeeHolidaysForm(instance=carry_over_holidays)

    context = {
        "employee": employee,
        "leaveList": leaveList,
        "attendanceList": attendanceList,
        "jobHistory": jobHistory,
        "documents": documents,
        "form": form,
        "phones": phones,
        "tablets": tablets,
        "sims": sims,
        "other_devices": other_devices,
        "annual_leave": annual_leave,
        "holidays_form": holidays_form
    }
    return render(request, "employee/employeeDetail.html", context)


@ login_required
@ user_passes_test(userHasAccess,
                   login_url="/dashboard/",
                   redirect_field_name=None)
def employeeAddLeave(request, pk):
    """ Handles add/edit employee leave based on the PK/ID provided. """

    employee = get_object_or_404(Employee, id=pk)
    inlineForm = EmployeeLeaveInlineForm(instance=employee)

    # If request is POST, populate the inline form,
    # validates the form and save.
    if request.method == "POST":
        inlineForm = EmployeeLeaveInlineForm(request.POST, instance=employee)

        if inlineForm.is_valid():
            inlineForm.save()
            messages.success(request, "Employee leave updated successfully.")

            return redirect(f"/employee/{pk}")

        else:
            messages.error(request, "Error updating employee leave.")

    context = {
        "inlineForm": inlineForm,
        "employee": employee
    }
    return render(request, "employee/employeeLeave.html", context)


@ login_required
@ user_passes_test(userHasAccess,
                   login_url="/dashboard/",
                   redirect_field_name=None)
def employeeCreate(request):
    """
         Renders a new employee form and
         creates a new employee if form validation passes.
    """

    form = EmployeeModelForm()

    # If request is POST, validates the form and save.
    if request.method == "POST":

        form = EmployeeModelForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, "Employee created successfully.")

            return redirect("/employee")
        else:
            messages.error(request, form.errors)

    context = {
        "form": form
    }

    return render(request, "employee/employeeCreate.html", context)


@ login_required
@ user_passes_test(userHasAccess,
                   login_url="/dashboard/",
                   redirect_field_name=None)
def employeeUpdate(request, pk):
    """ Update an existing employee """

    employee = get_object_or_404(Employee, id=pk)
    form = EmployeeModelForm(instance=employee)
    carry_over_holidays = EmployeeHolidays.objects.filter(
        employee=employee).first()
    holidays_form = EmployeeHolidaysForm(instance=carry_over_holidays)
    annual_leave = calculate_annual_leave(employee)

    if request.method == "POST":

        form = EmployeeModelForm(request.POST, instance=employee)

        if form.is_valid():
            form.save()
            messages.success(request, "Employee updated successfully.")
            return redirect(f"/employee/{employee.id}")
        else:
            messages.error(
                request,
                ("Something went wrong. If the problem "
                 "persists contact support.")
            )

    context = {
        "employee": employee,
        "form": form,
        "annual_leave": annual_leave,
        "holidays_form": holidays_form,
        "carry_over_holidays": carry_over_holidays
    }

    return render(request, "employee/employeeUpdate.html", context)


@ login_required
@ user_passes_test(userHasAccess,
                   login_url="/dashboard/",
                   redirect_field_name=None)
def employeeDelete(request, pk):
    """ Delete an existing employee """

    try:
        employee = get_object_or_404(Employee, id=pk)
        employee.delete()
        messages.success(request, "Employee deleted successfully.")

    except Exception:
        messages.error(
            request,
            ("Sorry, something went wrong. "
             "If the problem persists contact support.")
        )

    finally:

        return redirect("/employee")


@ login_required
@ user_passes_test(userHasAccess,
                   login_url="/dashboard/",
                   redirect_field_name=None)
def employeeAddAttendance(request, pk):
    """ Handles Edit/Add attendance based on the PK/ID provided. """

    employee = get_object_or_404(Employee, id=pk)
    inlineForm = EmployeeAttendanceInlineForm(instance=employee)
    # If request is POST, populate the inline form,

employee/templates/employee/includes/employeeAssets.html
{% load crispy_forms_tags %}
{% comment %} Assets {% endcomment %}
<div class="accordion m-2" id="accordionAssets">
    <div class="accordion-item">
        <h2 class="accordion-header" id="headingAssets">
            
            <button
                class="accordion-button collapsed"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#collapseAssets"
                aria-expanded="true"
                aria-controls="collapseAssets"
            >
                Assets
            </button>
        </h2>
    <div
        id="collapseAssets"
        class="accordion-collapse collapse"
        aria-labelledby="headingAssets"
        data-bs-parent="#accordionAssets"
    >
        <div class="accordion-body">
            <fieldset>
                <table id="tableLeave" class="table table-hover table align-middle mt-2">
                    <thead>
                        <tr>
                        <th scope="col">Device Type</th>
                        <th scope="col">Serial Number</th>
                        <th scope="col">Location</th>
                        <th scope="col">Status</th>
                        <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% include "employee/includes/employeeAssetsList.html" %}
                    </tbody>
                </table>
            </fieldset>
        </div>
    </div>
</div>

employee/templates/employee/includes/employeeAssetsList.html
{% if phones %}
    {% for phone in phones %}
        <tr>
        <td>Phone</td>
        <td>{{phone.serial_number}}</td>
        <td>{{phone.location|upper}}</td>
        <td>{{phone.status|capfirst}}</td>
        <td class="text-center">
            <a
                href="{% url 'inventory:edit_device' device_type='phone' id=phone.id %}"
                class="btn btn-sm btn-info"
                target="_blank"
                ><i class="fas fa-search-plus"></i> Details</a
            >
        </td>
        </tr>
    {% endfor %}
{% endif %}

{% if tablets %}
    {% for tablet in tablets %}
        <tr>
        <td>Tablet</td>
        <td>{{tablet.serial_number}}</td>
        <td>{{tablet.location|upper}}</td>
        <td>{{tablet.status|capfirst}}</td>
        <td class="text-center">
            <a
                href="{% url 'inventory:edit_device' device_type='tablet' id=tablet.id %}"
                class="btn btn-sm btn-info"
                target="_blank"
                ><i class="fas fa-search-plus"></i> Details</a
            >
        </td>
        </tr>
    {% endfor %}
{% endif %}

{% if sims %}
    {% for sim in sims %}
        <tr>
        <td>SIM</td>
        <td>{{sim.serial_number}}</td>
        <td>{{sim.location|upper}}</td>
        <td>{{sim.status|capfirst}}</td>
        <td class="text-center">
            <a
                href="{% url 'inventory:edit_device' device_type='sim' id=sim.id %}"
                class="btn btn-sm btn-info"
                target="_blank"
                ><i class="fas fa-search-plus"></i> Details</a
            >
        </td>
        </tr>
    {% endfor %}
{% endif %}

{% if other_devices %}
    {% for other_device in other_devices %}
        <tr>
        <td>{{other_device.other_device_type|capfirst}}</td>
        <td>{{other_device.serial_number}}</td>
        <td>{{other_device.location|upper}}</td>
        <td>{{other_device.status|capfirst}}</td>
        <td class="text-center">
            <a
                href="{% url 'inventory:edit_device' device_type='other_device' id=other_device.id %}"
                class="btn btn-sm btn-info"
                target="_blank"
                ><i class="fas fa-search-plus"></i> Details</a
            >
        </td>
        </tr>
    {% endfor %}
{% endif %}

employee/templates/employee/includes/employeeAttendanceDetails.html
{% load crispy_forms_tags %}
{% comment %} Attendance Details {% endcomment %}
<div class="accordion m-2" id="accordionAttendanceDetails">
    <div class="accordion-item">
        <h2 class="accordion-header" id="headingAttendanceDetails">
            {% if isEditable == "true" %}   
            <button
                class="accordion-button"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#collapseAttendanceDetails"
                aria-expanded="true"
                aria-controls="collapseAttendanceDetails"
            >
                Attendance Details
            </button>
            {% else %}
            <button
                class="accordion-button collapsed"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#collapseAttendanceDetails"
                aria-expanded="true"
                aria-controls="collapseAttendanceDetails"
            >
                Attendance Details
            </button>
            {% endif %}
        </h2>
        {% if isEditable == "true" %}
        <div
            id="collapseAttendanceDetails"
            class="accordion-collapse collapse show"
            aria-labelledby="headingAttendanceDetails"
            data-bs-parent="#accordionAttendanceDetails"
        >
        {% else %}
        <div
            id="collapseAttendanceDetails"
            class="accordion-collapse collapse"
            aria-labelledby="headingAttendanceDetails"
            data-bs-parent="#accordionAttendanceDetails"
        >
        {% endif %}
            <div class="accordion-body">
                {% if isEditable == "true" %}
                <fieldset>
                {% else %}
                <fieldset disabled>
                {% endif %}
                    <table id="tableAttendance" class="table table-hover align-middle mt-2">
                        <thead>
                            <tr>
                            <th scope="col">Attendance Date</th>
                            <th class="status" scope="col">Status</th>
                            <th class="hours" scope="col">Hours</th>
                            <th scope="col">Additional Status</th>
                            <th scope="col">Additional Hours</th>
                            <th scope="col">Overtime Hours</th>
                            <th scope="col">Additional Notes</th>
                            {% if user.department.department_name == "HR" or user.department.department_name == "Management" or user.department.department_name == "Accounts" or user.is_superuser%}
                            <th scope="col"></th>
                            {% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for attendance in attendanceList %}
                            <tr>
                            <td>{{attendance.attendance_date|date:"d M Y"}}</td>
                            <td>{{attendance.status}}</td>
                            <td>{{attendance.hours_worked}}</td>
                            <td>{{attendance.additional_status}}</td>
                            <td>{{attendance.additional_hours_worked}}</td>
                            <td>{{attendance.overtime_hours}}</td>
                            <td class="text-truncate">{{attendance.notes}}</td>
                            {% if user.department.department_name == "HR" or user.department.department_name == "Management" or user.department.department_name == "Accounts" or user.is_superuser%}
                            <td class="text-center"><a href="{% url 'employee:deleteAttendance' pk=attendance.pk %}" 
                                onclick="return confirm('Are you sure you want to delete this attendance? This is irreversible');"><i class="fas fa-trash-alt text-danger"></i></a></td>
                            {% endif %}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </fieldset>
                <div class="text-end">
                    <a
                        href="{% url 'employee:employeeAddAttendance' pk=employee.pk %}"
                        class="btn btn-sm btn-warning"
                        ><i class="fas fa-edit"></i> Edit</a
                    >
                </div>
            </div>
        </div>
    </div>
</div>

employee/templates/employee/includes/employeeAttendanceForm.html
{% load crispy_forms_tags %}{% load static %}
<div class="accordion m-2" id="accordionAttendanceDetails">
    <div class="accordion-item">
        <h2 class="accordion-header" id="headingAttendanceDetails">
        {% if isEditable == "true" %}
        <button
            class="accordion-button"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#collapseAttendanceDetails"
            aria-expanded="true"
            aria-controls="collapseAttendanceDetails"
        >
            Attendance Details
        </button>
        {% else %}
        <button
            class="accordion-button collapsed"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#collapseAttendanceDetails"
            aria-expanded="true"
            aria-controls="collapseAttendanceDetails"
        >
            Attendance Details
        </button>   
        {% endif %}    
        </h2>
        {% if isEditable == "true" %}   
        <div
            id="collapseAttendanceDetails"
            class="accordion-collapse collapse show"
            aria-labelledby="headingAttendanceDetails"
            data-bs-parent="#accordionAttendanceDetails"
        >
        {% else %}
        <div
            id="collapseAttendanceDetails"
            class="accordion-collapse collapse"
            aria-labelledby="headingAttendanceDetails"
            data-bs-parent="#accordionAttendanceDetails"
        >
        {% endif %}
          <div class="accordion-body">
            {% if isEditable == "true" %}
            <fieldset>
            {% else %}
            <fieldset disabled>
            {% endif %}
            {{inlineForm.management_form}}
            {% comment %} This needs to be tested! {% endcomment %}
                {% for form in inlineForm %}
                {{form.id}}
                {% if form.instance.id == None %}
                <div class="container bg-light-blue p-3 mb-2">
                    <h3 class="h4">New Attendance</h3>
                {% else %}
                <div class="container bg-light p-3 mb-2">
                    {% endif %}
                    <div class="row">
                        <div class="col-sm-12 col-lg-2 mb-2">
                        {{ form.attendance_date|as_crispy_field }}
                        </div>
                        <div class="col-sm-12 col-lg-2 mb-2">
                        {{ form.status|as_crispy_field }}
                        </div>
                        <div class="col-sm-12 col-lg-1 mb-2">
                        {{ form.hours_worked|as_crispy_field }}
                        </div>
                        <div class="col-sm-12 col-lg-2 mb-2">
                        {{ form.additional_status|as_crispy_field }}
                        </div>
                        <div class="col-sm-12 col-lg-3 mb-2">
                        {{ form.additional_hours_worked|as_crispy_field }}
                        </div>
                        <div class="col-sm-12 col-lg-2 mb-2">
                        {{ form.overtime_hours|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                        {{ form.notes|as_crispy_field }}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </fieldset>
        </div>
    </div>
</div>
{% block extraScripts %}
<script src="{% static 'employee/scripts.js'%}"></script>
{% endblock extraScripts%}

employee/templates/employee/includes/employeeContactDetails.html
{% load crispy_forms_tags %}
{% comment %} Contact Details {% endcomment %}

<div class="row mb-2">
  <div class="col-sm-12 col-lg-2 mb-2">
    {{ form.personal_phone|as_crispy_field }}
  </div>
  <div class="col-sm-12 col-lg-4 mb-2">
    {{ form.personal_email|as_crispy_field }}
  </div>
</div>
<div class="row mb-2">
  <div class="col-sm-12 col-lg-2 mb-2">
    {{ form.work_phone|as_crispy_field }}
  </div>
  <div class="col-sm-12 col-lg-4 mb-2">
    {{ form.work_email|as_crispy_field }}
  </div>
</div>

employee/templates/employee/includes/employeeEmergencyContact.html
{% load crispy_forms_tags %}
{% comment %} Emergency Contact {% endcomment %}
<div class="row mb-2">
  <div class="col-sm-12 col-lg-2 mb-2">
    {{ form.kin_first_name|as_crispy_field }}
  </div>
  <div class="col-sm-12 col-lg-4 mb-2">
    {{ form.kin_last_name|as_crispy_field }}
  </div>
  <div class="col-sm-12 col-lg-6 mb-2">
    {{ form.kin_relationship|as_crispy_field }}
  </div>
</div>
<div class="row mb-2">
  <div class="col-sm-12 col-lg-2 mb-2">
    {{ form.kin_phone|as_crispy_field }}
  </div>
  <div class="col-sm-12 col-lg-4 mb-2">
    {{ form.kin_email|as_crispy_field }}
  </div>
</div>
        

employee/templates/employee/includes/employeeHolidaysForm.html
{% extends "base.html" %}{% load static %}{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-5 mb-5">
    <div class="row">
        <h1 class="pl-2">Update Holidays Carry Over</h1>
    </div>
    <div class="text-start ms-2 mb-2">
        <a href="{% url 'employee:employeeDetail' pk=employee_id %}"><i class="fas fa-angle-left"></i> Back to Employee</a>
    </div>
    <hr>
    <div class="container shadow-sm rounded p-4 bg-light">
        <form  method="POST">
        {% csrf_token %}
            <div class="row">
                <div class="col-sm-12 col-lg-2">
                    {{form.carry_over_hours|as_crispy_field}}
                </div>
                <div class="col-sm-12 col-lg-2">
                    {{form.carry_over_expiry_date|as_crispy_field}}
                </div>
            <div class="text-end">
                <button type="submit" class="btn btn-sm btn-success"><i class="fas fa-check-circle"></i> Submit</button>
            </div>
            </div>
        </form>
    </div>
</div> 
{% endblock content %}

employee/templates/employee/includes/employeeJobHistoryDetails.html
{% load crispy_forms_tags %}
{% comment %} Job History Details {% endcomment %}
<table id="tableLeave" class="table table-hover table align-middle mt-2">
    <thead>
        <tr>
        <th scope="col">Start Date</th>
        <th scope="col">End Date</th>
        <th scope="col">Tenure</th>
        <th scope="col">Role</th>
        <th scope="col">Department</th>
        <th scope="col">Sub Department</th>
        </tr>
    </thead>
    <tbody>
        {% for job in jobHistory %}
        <tr>
        <td>{{job.role_start|date:"d M Y"}}</td>
        <td>{{job.role_end|date:"d M Y"}}</td>
        {% if job.role_end %}
            <td>{{job.role_start|timesince:job.role_end}}</td>
        {% else %}
            <td>{{job.role_start|timesince}}
        {% endif %}
        <td>{{job.role}}</td>
        <td>{{job.department}}</td>
        <td>{{job.sub_department}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<div class="text-end">
    <a
        href="{% url 'employee:employeeJobHistory' pk=employee.pk %}"
        class="btn btn-sm btn-warning"
        ><i class="fas fa-edit"></i> Edit</a
    >
</div>

employee/templates/employee/includes/employeeLeaveDetails.html
{% load crispy_forms_tags %}
{% comment %} Leave Details {% endcomment %}
<table id="tableLeave" class="table table-hover table align-middle mt-2">
    <thead>
        <tr>
        <th scope="col">Start Date</th>
        <th scope="col">End Date</th>
        <th scope="col">Leave Type</th>
        <th scope="col">Clawback/Deductions</th>
        <th scope="col">Additional Notes</th>
        </tr>
    </thead>
    <tbody>
        {% for leave in leaveList %}
        <tr>
            <td>{{leave.start_date|date:"d M Y"}}</td>

            {% if leave.end_date %}
                <td>{{leave.end_date|date:"d M Y"}}</td>
            {% else %}
                <td>-</td>
            {% endif %}

            <td>{{leave.leave_type}}</td>
            
            {% if leave.has_deduction == False %}
                <td>No</td>
            {% else %}
                <td>Yes</td>
            {% endif %}

            <td class="text-truncate">{{leave.notes}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div class="text-end">
    <a
        href="{% url 'employee:employeeAddLeave' pk=employee.pk %}"
        class="btn btn-sm btn-warning"
        ><i class="fas fa-edit"></i> Edit</a
    >
</div>

employee/templates/employee/includes/employeeVisaDetails.html
{% load crispy_forms_tags %}
{% comment %} Visa Details {% endcomment %}

<div class="row mb-2">
  <div class="col-sm-12 col-lg-2 mb-2">
    {{ form.visa_no|as_crispy_field }}
  </div>
  <div class="col-sm-12 col-lg-2 mb-2">
    {{ form.visa_type|as_crispy_field }}
  </div>
  <div class="col-sm-12 col-lg-2 mb-2">
    {{ form.visa_expiry|as_crispy_field }}
  </div>
</div>

    